export const LocalizedMetadata = {
  en: {
    title: "MuscleMap",
    description: "Modern fitness coaching platform with comprehensive exercise database and muscle mapping",
    keywords: [
      "fitness",
      "workout",
      "exercise",
      "training",
      "muscle building",
      "strength training",
      "bodybuilding",
      "fitness app",
      "workout planner",
      "exercise database",
      "muscle mapping",
      "bicep curl",
    ],
    ogAlt: "MuscleMap - Modern fitness platform with muscle mapping",
    applicationName: "MuscleMap",
    category: "fitness",
    classification: "Fitness & Health",
  },
  fr: {
    title: "MuscleMap",
    description: "Plateforme de coaching fitness moderne avec base de données d'exercices complète et cartographie musculaire",
    keywords: [
      "fitness",
      "entraînement",
      "exercice",
      "musculation",
      "sport",
      "coaching",
      "programme d'entraînement",
      "application fitness",
      "planificateur d'entraînement",
      "base de données d'exercices",
      "cartographie musculaire",
      "curl biceps",
    ],
    ogAlt: "MuscleMap - Plateforme de fitness moderne avec cartographie musculaire",
    applicationName: "MuscleMap",
    category: "fitness",
    classification: "Fitness et Santé",
  },
  es: {
    title: "MuscleMap",
    description: "Plataforma moderna de entrenamiento fitness con base de datos completa de ejercicios y mapeo muscular",
    keywords: [
      "fitness",
      "entrenamiento",
      "ejercicio",
      "musculación",
      "deporte",
      "coaching",
      "programa de entrenamiento",
      "aplicación fitness",
      "planificador de entrenamientos",
      "base de datos de ejercicios",
      "mapeo muscular",
      "curl de bíceps",
    ],
    ogAlt: "MuscleMap - Plataforma de fitness moderna con mapeo muscular",
    applicationName: "MuscleMap",
    category: "fitness",
    classification: "Fitness y Salud",
  },
  pt: {
    title: "MuscleMap",
    description: "Plataforma moderna de coaching fitness com base de dados abrangente de exercícios e mapeamento muscular",
    keywords: [
      "fitness",
      "treino",
      "exercício",
      "musculação",
      "esporte",
      "coaching",
      "programa de treino",
      "aplicativo fitness",
      "planejador de treinos",
      "base de dados de exercícios",
      "mapeamento muscular",
      "rosca bíceps",
    ],
    ogAlt: "MuscleMap - Plataforma de fitness moderna com mapeamento muscular",
    applicationName: "MuscleMap",
    category: "fitness",
    classification: "Fitness e Saúde",
  },
  ru: {
    title: "MuscleMap",
    description: "Современная платформа фитнес-коучинга с comprehensive базой данных упражнений и картированием мышц",
    keywords: [
      "фитнес",
      "тренировка",
      "упражнение",
      "бодибилдинг",
      "спорт",
      "коучинг",
      "программа тренировок",
      "фитнес приложение",
      "планировщик тренировок",
      "база данных упражнений",
      "картирование мышц",
      "подъем на бицепс",
    ],
    ogAlt: "MuscleMap - Современная фитнес платформа с картированием мышц",
    applicationName: "MuscleMap",
    category: "фитнес",
    classification: "Фитнес и Здоровье",
  },
  "zh-CN": {
    title: "MuscleMap",
    description: "现代健身教练平台，拥有全面的运动数据库和肌肉映射",
    keywords: ["健身", "锻炼", "运动", "训练", "肌肉训练", "力量训练", "健美", "健身应用", "锻炼计划", "运动数据库", "肌肉映射", "二头肌弯举"],
    ogAlt: "MuscleMap - 现代健身平台与肌肉映射",
    applicationName: "MuscleMap",
    category: "健身",
    classification: "健身与健康",
  },
} as const;

export type SupportedLocale = keyof typeof LocalizedMetadata;

export function getLocalizedMetadata(locale: string) {
  const supportedLocales: SupportedLocale[] = ["en", "fr", "es", "pt", "ru", "zh-CN"];

  if (supportedLocales.includes(locale as SupportedLocale)) {
    return LocalizedMetadata[locale as SupportedLocale];
  }

  return LocalizedMetadata.en;
}
